version : '1.0'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - pong-network
    volumes:
      - frontend_dist:/app/dist
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - pong-network
    ports:
      - "80:80"
    depends_on:
      - frontend
    restart: always;

  backend:
    build: ./backend
    container_name: backend
    networks:
      - pong-network
    expose:
      - "3000"
    restart: always;

  mariadb:
    build: ./mariadb
    container_name: mariadb
    networks:
      - pong-network
    env_file:
      - ../secrets/.env
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always;

volumes:
  mariadb_data:
  frontend_dist:

networks:
  pong-network:
